config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    resource :like, module: :posts
  end

  resources :albums do
    resource :like, module: :albums
  end

  namespace :admin do
    resources :users
    get 'admin/user/change/:id', to: 'users#change_status', as: 'change_status'
  end

  get 'user/timeline/:id', to: 'albums#my_photos', as: 'timeline'

  devise_for :users
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user

  has_many :posts, dependent: :destroy
  has_many :likes, as: :love, dependent: :destroy

  scope :privated, -> { where.not(title: 'Default', private: true) }
  scope :published, ->(params_id) { where(user_id: params_id) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :love, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  STYLES_IMAGE = { medium: '300x300>', thumb: '100x100>' }.freeze
  CONTENT_TYPE_IMAGE = /\Aimage\/.*\Z/

  belongs_to :album
  has_many :likes, as: :love, dependent: :destroy

  validates :image, presence: true
  has_attached_file :image, styles: STYLES_IMAGE
  do_not_validate_attachment_file_type :image
  validates_attachment_content_type :image, content_type: CONTENT_TYPE_IMAGE

  scope :published, -> { where(album_id: Album.where(title: 'Default').pluck(:id), private: false) }
end

app/models/user.rb
class User < ApplicationRecord
  USER_NAME_MAXLENGTH = 32
  USER_NAME_MINLENGTH = 4

  has_many :albums, dependent: :destroy
  has_many :posts, through: :albums, dependent: :destroy
  has_many :likes, as: :love, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :user_name, presence: true,
                        length:
                        {
                          minimum: USER_NAME_MINLENGTH,
                          maximum: USER_NAME_MAXLENGTH
                        }

  after_create do |user|
    user.albums.create(title: 'Default', description: 'Default album')
  end

  def active_for_authentication?
    super && active?
  end

  def likes?(post)
    post.likes.where(user_id: id).any?
  end

  def likes_album?(album)
    album.likes.where(user_id: id).any?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_service
  before_action :set_user, only: %i[destroy change_status]

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  def change_status
    @admin_service.change_status_user(@user)
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def admin_service
    @admin_service ||= AdminService.new
  end
end

app/controllers/albums/likes_controller.rb
class Albums::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :like_service
  before_action :set_album

  def new
    @like = Like.new
  end

  def create
    @like_service.like(@album, current_user.id)
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    @like_service.unlike(@album, current_user.id)
    respond_to do |format|
      format.js {}
    end
  end

  private

  def set_album
    @album = Album.find(params[:album_id])
  end

  def like_service
    @like_service ||= LikeService.new
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :album_service
  before_action :set_album, only: %i[show edit update destroy]
  before_action :check_authority, only: %i[update destroy edit]

  def new
    @album = Album.new
  end

  def index
    @albums =  @album_service.create_index(params)
  end

  def my_photos
    @albums =  @album_service.create_dashbroad(params)
  end

  def create
    if @album_service.create_album(current_user, album_params, params)
      redirect_to albums_path
    else
      render :new
    end
  end

  def update
    @album.update(album_params)
    redirect_to albums_path
  end

  def destroy
    @album.destroy
    redirect_to albums_path
  end

  private

  def album_params
    params.require(:album).permit(:title, :description, :images, :private)
  end

  def set_album
    @album = Album.find(params[:id])
  end

  def check_authority
    (@album.user_id == current_user.id) || current_user.admin?
  end

  def album_service
    @album_service ||= AlbumService.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery prepend: true

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:user_name,
                         :email,
                         :password,
                         :password_confirmation,
                         :admin)
    end
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :like_service
  before_action :set_post
  def new
    @like = Like.new
  end

  def create
    @like_service.like(@post, current_user.id)
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    @like_service.unlike(@post, current_user.id)
    respond_to do |format|
      format.js {}
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def like_service
    @like_service ||= LikeService.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :post_service
  before_action :set_post, only: %i[show edit update destroy]
  before_action :check_authority, only: %i[update destroy edit]

  def new
    @post = Post.new
  end

  def index
    @posts = @post_service.create_index(params)
  end

  def create
    if @post_service.create_post(current_user, post_params)
      redirect_to
    else
      render :new
    end
  end

  def update
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :image, :private)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def check_authority
    (@post.album.user_id == current_user.id) || current_user.admin?
  end

  def post_service
    @post_service ||= PostService.new
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def owner_album(album)
    User.find_by_id(album.user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def maketitle(ptitle = '')
    "#{ptitle}|Final App"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def owner_post(post)
    User.find_by_id(post.album.user_id)
  end
end

app/views/admin/users/index.html.slim
- provide(:title, "List of Users")
h1.text-center
  | List of Users
table.table.table-striped.table-hover
  thead
    tr
      th
        | Name
      th
        | Email
      th
        | Status
      th[colspan="2"]
        | Manipulation
  tbody
    - @users.each do |user|
      - if !user.admin?
        tr
          td
            = user.user_name
          td
            = user.email
          - if user.active
            td
              = link_to "Enable", admin_change_status_path(user.id),data: {confirm: t(:disable_user) }
          - else
            td
              = link_to "Disable", admin_change_status_path(user.id),data: {confirm: t(:enable_user) }
          td
            = link_to 'Destroy', admin_user_path(user), method: :delete , data: {confirm: t(:delete_user) }
          td
            = link_to 'Timeline', timeline_path(user)

app/views/albums/_likes.html.slim
- if user_signed_in? && current_user.likes_album?(album)
  = form_tag album_like_path(album.id), method: :delete, remote: true do
    div
      = button_to 'Unlike','#', class: "btn btn-danger", remote: true
- else
  = form_tag album_like_path(album.id), method: :post, remote: true do
    div
      = button_to 'Like','#', class: "btn btn-success", remote: true
= album.likes.size

app/views/albums/edit.html.slim
- provide(:title, "Edit album")
.container
  .row
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          p.text-center
            | Edit Album
        .panel-body
          = form_for @album,:html => { multipart: true } do |f|
            .form-group
              = f.label "Album name"
              = f.text_field :title, class: "form-control"
            .form-group
              = f.label :description
              = f.text_field :description, class: "form-control"
            .form-group
              = f.label :images
              = file_field_tag "images[]", type: :file, multiple: true
            .form-group
              = f.label "Private"
              = f.check_box :private
            = link_to "Back", albums_path, class: "btn btn-default"
            = f.submit "Edit Album", class: "btn btn-default pull-right"

app/views/albums/index.html.slim
- provide(:title, "Albums")
- @albums.each do |album|
  .panel.panel-info
    .panel-heading
      = link_to owner_album(album).user_name, timeline_path(owner_album(album).id)
    .panel-body
      div
        h4
          = album.title
        - if current_user.id == album.user_id || current_user.admin?
          .dropdown.pull-right
            button#dropdownMenu1.btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"]
              span.glyphicon.glyphicon-option-horizontal
            ul.dropdown-menu.dropdown-menu-right[aria-labelledby="dropdownMenu1"]
              li
                a
                  = link_to 'Edit', edit_album_path(album.id)
              li
                a
                  = link_to 'Delete', album_path(album.id), method: :delete, data: {confirm: t(:delete_post) }
      div[style="text-align: center;"]
        - album.posts.each do |post|
          div[style="display: inline-block;"]
            = link_to (image_tag post.image.url(:thumb)), album_path(album.id)
      .description
        = album.description
      div id="album_#{album.id}_likes"
          = render partial: 'albums/likes', locals: {album: album}
.text-center
  = paginate @albums

app/views/albums/likes/create.js.slim
| $("#album_
= @album.id
| _likes").html("
=j render partial: 'albums/likes', locals: {album: @album}
| ");

app/views/albums/likes/destroy.js.slim
| $("#album_
= @album.id
| _likes").html("
=j render partial: 'albums/likes', locals: {album: @album}
| ");

app/views/albums/my_photos.html.slim
- provide(:title, "Timeline")
- @albums.each do |album|
  - if !album.private || current_user.id == album.user_id || current_user.admin?
    .panel.panel-info
      .panel-heading
        = User.find_by_id(album.user_id).user_name
      .panel-body
        div
          h4
            = album.title
          - if (current_user.id == album.user_id || current_user.admin?) && album.title != "Default"
            .dropdown.pull-right
              button#dropdownMenu1.btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"]
                span.glyphicon.glyphicon-option-horizontal
              ul.dropdown-menu.dropdown-menu-right[aria-labelledby="dropdownMenu1"]
                li
                  a
                    = link_to 'Edit', edit_album_path(album.id)
                li
                  a
                    = link_to 'Delete', album_path(album.id), method: :delete, data: {confirm: t(:delete_album) }
        div[style="text-align: center;"]
          - album.posts.each do |post|
            div[style="display: inline-block;"]
              = link_to (image_tag post.image.url(:thumb)), album_path(album.id)
        .description
          = album.description
        div id="album_#{album.id}_likes"
          = render partial: 'albums/likes', locals: {album: album}
.text-center
  = paginate @albums

app/views/albums/new.html.slim
- provide(:title, "Create new album")
.container
  .row
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          p.text-center
            | Create Album
        .panel-body
          = form_for @album,:html => { multipart: true } do |f|
            .form-group
              = f.label "Album name"
              = f.text_field :title, class: "form-control"
            .form-group
              = f.label :description
              = f.text_field :description, class: "form-control"
            .form-group
              = f.label :images
              = file_field_tag "images[]", type: :file, multiple: true
            .form-group
              = f.label "Private"
              = f.check_box :private
            = link_to "Back", posts_path, class: "btn btn-default"
            = f.submit "Create Album", class: "btn btn-default pull-right"

app/views/albums/show.html.slim
- provide(:title, "Album " + @album.title)
- @album.posts.each do |post|
  .panel.panel-info
    .panel-heading
      = link_to owner_post(post).user_name, timeline_path(owner_post(post).id)
    .panel-body
      div
        h4
          = post.title
        - if current_user.id == post.album.user_id || current_user.admin?
          .dropdown.pull-right
            button#dropdownMenu.btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"]
              span.glyphicon.glyphicon-option-horizontal
            ul.dropdown-menu.dropdown-menu-right[aria-labelledby="dropdownMenu"]
              li
                a
                  = link_to 'Edit', edit_post_path(post)
              li
                a
                  = link_to 'Delete', post_path(post), method: :delete, data: {confirm: t(:delete_post) }
      = image_tag post.image.url, class:'img-responsive center-block'
      .description
        = post.description
      div id="post_#{post.id}_likes"
          = render partial: 'posts/likes', locals: {post: post}

app/views/layouts/_nav.html.slim
.container
  .header.clearfix
    nav
      ul.nav.nav-pills.pull-right[style="margin: 10px;"]
        li[role="presentation"]
          = link_to 'Post', posts_path
        li[role="presentation"]
          = link_to 'Album', albums_path
        - if user_signed_in?
          li[role="presentation"]
            = link_to 'My Photos', timeline_path(current_user.id)
          - if current_user.admin?
            li[role="presentation"]
              = link_to 'Users List', admin_users_path
        li.dropdown[role="presentation"]
          a.dropdown-toggle[data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"]
            span.glyphicon.glyphicon-user[aria-hidden="true"]
            - if user_signed_in?
              = current_user.user_name
            - else
              |  User 
            span.caret
          ul.dropdown-menu
            - if user_signed_in?
              li
                = link_to "New Post", new_post_path
              li
                = link_to "New Album", new_album_path
              li
                = link_to "Logout", destroy_user_session_path, method: :delete
            - else
              li
                = link_to "Login", new_user_session_path
              li
                = link_to "Register", new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      =maketitle(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/nav"
    .container
      = yield

app/views/posts/_likes.html.slim
- if user_signed_in? && current_user.likes?(post)
  = form_tag post_like_path(post.id), method: :delete, remote: true do
    div
      = button_to 'Unlike','#', class: "btn btn-danger", remote: true
- else
  = form_tag post_like_path(post.id), method: :post, remote: true do
    div
      = button_to 'Like','#', class: "btn btn-success", remote: true
= post.likes.size

app/views/posts/edit.html.slim
- provide(:title, "Edit post")
.container
  .row
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          p.text-center
            | Edit post
        .panel-body
          = form_for @post do |f|
            .form-group
              = f.label :title
              = f.text_field :title, class: "form-control"
            .form-group
              = f.label :description
              = f.text_field :description, class: "form-control"
            .form-group
              = f.label :image
              = f.file_field :image
            .form-group
              = f.label "Private"
              = f.check_box :private
            = link_to "Back", posts_path, class: "btn btn-default"
            = f.submit "Update", class: "btn btn-default pull-right"

app/views/posts/index.html.slim
- provide(:title, "Posts")
- @posts.each do |post|
  - if !post.private || current_user.id == post.album.user_id || current_user.admin?
    .panel.panel-info
      .panel-heading
        = link_to owner_post(post).user_name, timeline_path(owner_post(post).id)
      .panel-body
        div
          h4
            = post.title
          - if current_user.id == post.album.user_id || current_user.admin?
            .dropdown.pull-right
              button#dropdownMenu.btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"]
                span.glyphicon.glyphicon-option-horizontal
              ul.dropdown-menu.dropdown-menu-right[aria-labelledby="dropdownMenu"]
                li
                  a
                    = link_to 'Edit', edit_post_path(post.id)
                li
                  a
                    = link_to 'Delete', post_path(post.id), method: :delete, data: {confirm: t(:delete_post) }
        = link_to (image_tag post.image.url, class:'image img-responsive center-block'), post_path(post.id)
        .description
          = post.description
        div id="post_#{post.id}_likes"
          = render partial: 'posts/likes', locals: {post: post}
.text-center
  = paginate @posts

app/views/posts/likes/create.js.slim
| $("#post_#{@post.id}
| _likes").html("
=j render partial: 'posts/likes', locals: {post: @post}
| ");

app/views/posts/likes/destroy.js.slim
| $("#post_
= @post.id
| _likes").html("
=j render partial: 'posts/likes', locals: {post: @post}
| ");

app/views/posts/new.html.slim
- provide(:title, "Create new post")
.container
  .row
    .col-md-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          p.text-center
            | Create Post
        .panel-body
          = form_for @post do |f|
            .form-group
              = f.label :title
              = f.text_field :title, class: "form-control"
            .form-group
              = f.label :description
              = f.text_field :description, class: "form-control"
            .form-group
              = f.label :image
              = f.file_field :image
            .form-group
              = f.label "Private"
              = f.check_box :private
            = link_to "Back", posts_path, class: "btn btn-default"
            = f.submit "Post", class: "btn btn-default pull-right"

app/views/posts/show.html.slim
- provide(:title, "Post")
.panel.panel-info
  .panel-heading
    = link_to owner_post(@post).user_name, timeline_path(owner_post(@post).id)
  .panel-body
    div
      h4
        = @post.title
      - if current_user.id == @post.album.user_id || current_user.admin?
        .dropdown.pull-right
          button#dropdownMenu.btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"]
            span.glyphicon.glyphicon-option-horizontal
          ul.dropdown-menu.dropdown-menu-right[aria-labelledby="dropdownMenu"]
            li
              a
                = link_to 'Edit', edit_post_path(@post.id)
            li
              a
                = link_to 'Delete', post_path(@post.id), method: :delete, data: {confirm: t(:delete_post) }
    = image_tag @post.image.url, class:'img-responsive center-block'
    .description
      = @post.description
    div id="post_#{@post.id}_likes"
          = render partial: 'posts/likes', locals: {post: @post}